name: Check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: fmt
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      
      - name: install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: install taplo
        run: cargo install taplo-cli

      - name: run Rust fmt
        run: cargo fmt --all -- --check

      - name: run TOML fmt
        run: taplo fmt --check

  check:
    name: Build and Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: check/ubuntu

      - name: Build
        run: cargo build --workspace

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- --deny warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: check/test/ubuntu

      - name: Run tests
        run: cargo test --verbose --workspace